### PR TITLE
Added Vectary as a tool for 3D and AR online.

### PR DESCRIPTION
**Pull request by milangladis**

### CODE REVIEW

**Comment by LisaDziuba** [comment]
@milangladis hey Milan! Thanks for your submission :)
Please put the Vectary in the alphabetical order. We treat all tools equally, so it will be nice to keep that. 

Thanks!

**Comment by LisaDziuba** [comment]
and congrats with your first Pull Request 💐

**Comment by milangladis** [comment]
Hi @LisaDziuba 👋thanks for the review ;)
I changed the order of tools in Augmented reality section.

**Comment by LisaDziuba** [comment]
Added 👌
Thanks for contribution!

**Pull request merged**
