### PR TITLE
Add Logo Maker tool to Logo Design

### PR DESCRIPTION
**Pull request by designhill**
Checklist

* [x] I made something good today 💐.
* [x] I put links in the correct format: ``[Tool](link) — description.``
* [x] My description starts with the upper-case letter and because it's starting with the tool name and end with the full stop.
* [x] I put the tool in the alphabetical order.

## Optional

* [x] I added the appropriate labels: open-source or mac.
* [x] I put the tool only to one category.
* [x] I followed [Contribution Guidelines](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/Contribution_Guidelines.md#one-tool-can-go-only-to-one-category). 
[Code.txt](https://github.com/LisaDziuba/Awesome-Design-Tools/files/3021523/Code.txt)

### CODE REVIEW

**Comment by designhill** [comment]
Hi Lisa,

I am new at Github and not much familiar with this. So I requested to add Logo Maker tool but didn't know where to place or add tool link with description. So I have attached required details in a attachment name as **"Code.txt"**.

Please let me know if anything needed from me.

Thanks

**Comment by designhill** [comment]
I have some updation in description so please let me know how can i update it.

Thanks

**Comment by valianka** [comment]
@designhill hey, thanks for your contribution, but your submission is wrong. Could you please, add your tool again?

**Comment by LisaDziuba** [comment]
hey @designhill 🖐
Using GitHub is not easy for the first time, so it's fine. As @valianka mentioned, when you submitted your tool you accidentally deleted all other tools. For not making a lot of fixes, I just will close your submission and add your tool by myself. That's easy to do.

**Comment by LisaDziuba** [comment]
Closing your Pull Request and already added your tool with such description:

* [Logo Maker](https://www.designhill.com/tools/logo-maker) by Designhill — generate 1000s of unique logos in only few minutes, without design expertise. If you wish to change it, just write the test you want in the comment under this discussion. Then I'll change it myself.

Thanks, Lisa

**Comment by designhill** [comment]
Thanks for your support Lisa! I really appreciate this. Please update tool description as follows:

[Logo Maker](https://www.designhill.com/tools/logo-maker) — Logo Maker tool uses artificial intelligence to generate 1000s of unique logos in a few minutes. No design expertise required. Only pay when you find a design you love.

**Comment by valianka** [comment]
hey, @designhill, I'll update your description, but here are some recommendations:

1. There are a lot of the same names, so it's better to mention "Logo Maker by Designhill" to make others recognize your tool.
2. It'll be better to make the description shorter. 
3. We use labels (free, mac only, open-source). That's why you shouldn't notice about pricing.

[Logo Maker](https://www.designhill.com/tools/logo-maker) by Designhill — this tool uses artificial intelligence to generate 1000s of unique logos in a few minutes. 

What do you think about these improvements?

**Comment by designhill** [comment]
Can you update this text:

Logo Maker by Designhill — this tool uses artificial intelligence to generate 1000s of unique logos in a few minutes. No design expertise required.

**Pull request closed without merging**
