### PR TITLE
Add Keyshape

### PR DESCRIPTION
**Pull request by sqott**
Adding [Keyshape](https://www.keyshapeapp.com/) into animation tools. Great tool to export animated SVGs.

### CODE REVIEW

**Comment by LisaDziuba** [comment]
hey @sqott :)
Some follow up question to you, please:

* add a full stop at the end of the sentence 
* add labels for Mac tool 
<details>

image

see [Contribution Guidlines](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/Contribution_Guidelines.md)

</details>

**Comment by LisaDziuba** [comment]
And thanks for another edits with spaces 🤣

**Comment by sqott** [comment]
@LisaDziuba you got it!

**Comment by LisaDziuba** [comment]
@sqott 
Scott, you are awesome 😉

**Pull request merged**
