### PR TITLE
Added UI Faces plugin for Sketch and Adobe XD

### PR DESCRIPTION
**Pull request by perfectflow**
## Checklist

* [x] I made something good today 💐.
* [x] I put links in the correct format: ``[Tool](link) — description.``
* [x] My description starts with the lower-case letter and ends with the full stop.
* [x] I put the tool in the alphabetical order.

## Optional

* [ ] I added the appropriate labels: free, open-source or mac.
* [x] I put the tool only to one category.
* [x] I followed [Contribution Guidelines](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/Contribution_Guidelines.md#one-tool-can-go-only-to-one-category).

### CODE REVIEW

**Comment by LisaDziuba** [comment]
@perfectflow I will add it tomorrow

**Comment by perfectflow** [comment]
Why aren't you adding UI Faces?

**Comment by LisaDziuba** [comment]
it has conflicts in the branch and I need to resolve it 😩 Sorry for being so slow

**Comment by LisaDziuba** [comment]
I just added your plugin as a new PR.

**Pull request closed without merging**
