### PR TITLE
Add Emporter to Collaboration Tools

### PR DESCRIPTION
**Pull request by mikepulaski**
## Checklist

* [x] I made something good today 💐.
* [x] I put links in the correct format: ``[Tool](link) — description.``
* [x] My description starts with the lower-case letter and ends with the full stop.
* [x] I put the tool in the alphabetical order.

## Optional

* [x] I added the appropriate labels: free, open-source or mac.
* [x] I put the tool only to one category.
* [x] I followed [Contribution Guidelines](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/Contribution_Guidelines.md#one-tool-can-go-only-to-one-category).

### CODE REVIEW

**Comment by LisaDziuba** [comment]
@mikepulaski thanks for sending PR. I'm not sure it's collaboration tool or have  direct\indirect relationship to the design. 

Let's ask @valianka and @ribadima, what do they think 🤔

**Comment by mikepulaski** [comment]
Hi @LisaDziuba! Thanks for your feedback. If you, @valianka or @ribadima think it's more appropriate in a different category, I can help tweak the description if needed.

**Comment by valianka** [comment]
@mikepulaski thanks for your suggestion. In spite of this, Emporter isn't 100% relevant to the collaboration tools section, that's why we can't add it.

**Comment by LisaDziuba** [comment]
yeah....
I think, we'll skip adding it as it's not related to design in direct\indirect way (not only to collaboration tools). Sorry 🙈

**Pull request closed without merging**
