### PR TITLE
UXPin - added info in categories that fit

### PR DESCRIPTION
**Pull request by jacekzlowocki**
UXPin is a complete design platform that has multiple tools to cover entire design process. Therefore it fits into multiple categories on the list.

I took a liberty to add informations about UXPin tools to other categories than just Prototyping.
UXPin also has the free plan that can be used with most of it's tools, so I've added _free_ label to those.

### CODE REVIEW

**Comment by valianka** [comment]
@jacekzlowocki, thanks for your pull request, but we couldn't add your product to all these sections. We can add it to the additional information under sections.

**Comment by LisaDziuba** [comment]
I agree with @valianka. The same case we had with Framer X, when they submitted Framer X Team Store, part of their product for Design Systems.

So I'll add UXPin to all relevant sections with links you added. Also, it makes sense to update Contribution Guidelines to clearly specify that one tool can be added only to one category and be listed as recommend under other sections.

**Comment by jacekzlowocki** [comment]
Got it, thank you!

I think that appearance of some other products (namely Invision) in multiple categories may create a perception of such approach being desired :)

**Comment by LisaDziuba** [comment]
@jacekzlowocki thanks for following up.

> I think that appearance of some other products (namely Invision) in multiple categories may create a perception of such approach being desired :)


thanks for pointing out! The list was formed by 64 people, so we have a lot of things to fix and review🙈 I will make  a task to clear all duplicates in the main sections and move that tools to just recommended sentence. 

Sorry to hear about InVision, we want to treat all tools equally. This will be fixed.

**Comment by jacekzlowocki** [comment]
I understand, great :) Thank you for your effort!

**Comment by valianka** [comment]
@jacekzlowocki I've removed duplicates and added UXPin to our collection! 🎉🎉🎉 Thanks for your contribution!!

**Pull request merged**
