### PR TITLE
add VisBug

### PR DESCRIPTION
**Pull request by argyleink**
does a lot of things, but fit very nicely into these 2 areas

### CODE REVIEW

**Comment by argyleink** [comment]
Problem? 2 areas? I could pick just 1.
If you haven't tried it, it does in 1 tool what a few do that are in the list. It's super handy, but def different.

**Comment by argyleink** [comment]
and feedback about not accepting would be great

**Comment by LisaDziuba** [comment]
hey @argyleink Adam!
Sorry for such a delay in reviewing. 

We decided to add your tool in a new category of Visual Debugging. And made a rule to add future new categories with 2+ tools. That happens because people submitted many new categories with one tool, which was fine at the beginning and then became a mess 😅

Today someone over Twitter suggested another tool, which might go very well to Visual Debugging section. So **I added VisBug** to the new category and as a recommended tool to the Accessibility category (indeed, we saw an issue with tools being mentioned in many categories, fixed that and added note in Contribution Guidelines).

VisBug is a great and powerful tool. I wish you luck in getting many great users 💛 I'm closing the PR, as I have added VisBug already:

image


image

**Comment by argyleink** [comment]
thanks for the update! grats on the success of the repo and thanks for posting VisBug!

**Pull request closed without merging**
