### PR TITLE
Adding Whiteboard, RealtimeBoard

### PR DESCRIPTION
**Pull request by ribadima**
Adding to "User Flow Tools" topic

* [Witeboard](https://www.witeboard.com/)
* [RealtimeBoard](https://www.realtimeboard.com/)

### CODE REVIEW

**Comment by LisaDziuba** [comment]
@ribadima maybe it should go to "Collaboration Section" (which we can make)?
We use RealtimeBoard for idealisation, planning, collecting insights from user interviews.

So it's not only for User Flows. Maybe even, "Design Collaboration"

**Comment by ribadima** [comment]
Added Topic
- Collaboration Tools

**Comment by ribadima** [comment]
+
Fixed "-" to "—" for items description 
Fixed strange visual ident for "Color Picker Tools" topic items

**Comment by ribadima** [comment]
For the next document releases, you can use regex in GitHub search: /([ ])[-]([ ])/ 
(https://monosnap.com/file/yQQVrAlbgwOqN7IBlbV5QjdmYX7pvN)

Also see https://github.com/ChristophLabacher/fix-punctuation

**Comment by LisaDziuba** [comment]
@ribadima hey 😊

* thanks for "Collaboration Tools" section and Whiteboard & RealtimeBoard in it.
* thanks for fixing punctuation.
* we'll make a contribution guidelines soon, that will illuminate some mistakes as well.

**Pull request merged**
