### PR TITLE
Colours cafe add

### PR DESCRIPTION
**Pull request by oliver-gomes**
Colours cafe added for color picker section

### CODE REVIEW

**Comment by oliver-gomes** [comment]
@LisaDziuba when you get a change merge it, Thanks!

**Comment by LisaDziuba** [comment]
hey @oliver-gomes, I will review the tool now.

**Comment by LisaDziuba** [comment]
@oliver-gomes some follow up question:  

1) why have you decided to change `*` to `-` in the Markdown? 
2) I'm not sure about https://www.instagram.com/colours.cafe/ as it's an Intagram account not an actual tool. Let's ask community.

I will mention ppl who submitted another colour picker tools and ask their opinion. That should be a fair way.

Thanks again for contribution!

**Comment by oliver-gomes** [comment]
1. I didn't notice it, think my code editor changed it all at once
2. I found it really helpful and tool coming soon on their site

Thanks for the review, i will make sure in future the markdown doesn't change

**Comment by LisaDziuba** [comment]
hey! I talked to @valianka and other folks internally, we decided yo add Colour Cafe. I will close your PR and will add it by myself because I will need to fix too much small conflicts 😅

Thanks again for contribution and understanding!

**Comment by oliver-gomes** [comment]
@LisaDziuba Sure! My bad on that, will make sure my prettier plugin is turned off when making future changes 😃

**Pull request closed without merging**
