### PR TITLE
Add “Contrast” to Accessibility Tools

### PR DESCRIPTION
**Pull request by misolori**
This adds [Contrast](https://usecontrast.com/) to the accessibility tools section.

### CODE REVIEW

**Comment by valianka** [comment]
Hey, Miguel, many thanks for your contribution!
Contrast is a great tool, btw it has been already added to the accessibility tools section :)

**Comment by misolori** [comment]
Isn’t that one [Contraste](https://contrasteapp.com/)? That one is different from [Contrast](https://usecontrast.com/).

**Comment by LisaDziuba** [comment]
@misolori & @valianka, so we have something interesting here 👀 I will take a look now!

**Comment by LisaDziuba** [comment]
@misolori I'm sorry! it was indeed a new tool. Probably, we haven't noticed it as the names are very similar.

**Pull request merged**
