### PR TITLE
Add Naker Tools

### PR DESCRIPTION
**Pull request by valentinbdv**
## Checklist

* [x] I made something good today 💐.
* [x] I put links in the correct format: ``[Tool](link) — description.``
* [x] My description starts with the lower-case letter and ends with the full stop.
* [x] I put the tool in the alphabetical order.

## Optional

* [x] I added the appropriate labels: free, open-source or mac.
* [x] I put the tool only to one category.
* [x] I followed [Contribution Guidelines](https://github.com/LisaDziuba/Awesome-Design-Tools/blob/master/Contribution_Guidelines.md#one-tool-can-go-only-to-one-category).

### CODE REVIEW

**Comment by LisaDziuba** [comment]
hey @valentinbdv 
Maybe your tools will better sure 3D category?

**Comment by valentinbdv** [comment]
Hello Lisa. I also hesitate but the only 3D category you have is "3D Modeling Software" which is very specific. The tools I push would better fit in "Web Interactive Tools" or "3D Web Design Tools". Not sure what the best wording would be for your list. ;)

**Comment by valentinbdv** [comment]
In that category we could put other tools like these:
https://playcanvas.com/
http://www.layabox.com/
https://scapic.com/

Tell me what you think ;)

**Comment by valentinbdv** [comment]
Hello Lisa, how are you today? ;)

I just want to close that pull request so tell me what should I do?
If you prefer I can put the tools in the "3D Modeling Software".

Bye

**Comment by LisaDziuba** [comment]
hey @valentinbdv it was hard to choose the category as it's a bit 3D, a bit content creation and a bit web design. I decided to add your tools to animation. Hope it works

**Comment by valentinbdv** [comment]
Ok no problem! You better know what is the right place to put it. Plus we are sometimes compare to aftereffect but for the web! ;)

**Pull request merged**
